name: Decode Base64
on:
  push:
    branches:
      - main
jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq
      - name: Decode base64 content
        run: |
          # Replace 'base.txt' with the path to the file containing the URLs or base64 content
          content=$(cat base.txt)
          # Split content into lines
          IFS=$'\n' read -rd '' -a lines <<<"$content"
          # Initialize decoded content variable
          decoded_content=""
          # Process each line
          for line in "${lines[@]}"; do
            # Check if line is a URL
            if [[ $line =~ ^https?:// ]]; then
              echo "Line is a URL"
              # Retrieve content from URL
              line_content=$(curl -sL $line)
            else
              line_content=$line
            fi
            # Check if line content is base64 encoded
            if echo "$line_content" | base64 --decode | base64 --encode | grep -q "^$line_content\$"; then
              echo "Line content is base64 encoded"
              # Decode base64 content and append to decoded content variable
              decoded_content+=$(echo "$line_content" | base64 --decode)
            else
              echo "Line content is not base64 encoded"
            fi
          done
          # Save decoded content to file
          echo "$decoded_content" > decoded.txt
          echo "Decoded content saved to decoded.txt"
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add decoded.txt
          git commit -m "Decode base64 content"
          git push
