name: Decode Base64 Content
on:
  push:
    branches:
      - main
jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Clear decoded.txt
        run: echo "" > decoded.txt
      - name: Decode content
        run: |
          
          i=1
          while read link; do
            echo "Processing link: $link"
            content=$(curl -s $link)
            echo "Content retrieved from link: $content"
            if [[ $content =~ ^[A-Za-z0-9+/]+={0,2}$ ]]; then
              echo "Content is in Base64 format"
              echo $content | base64 --decode >> decoded.txt
            else
              echo "Content is not in Base64 format"
              echo $content >> decoded.txt
            fi
            i=$((i+1))
          done < Base.txt
      - name: Process decoded.txt
        run: |
          
          i=1
          while read line; do
            line=${line%%#*}
            line+="MIX-$i"
            echo $line >> processed.txt
            i=$((i+1))
          done < decoded.txt
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add decoded.txt processed.txt
          git commit -m "Update decoded content"
          git push origin main

