name: Decode Base64 Content
on:
  push:
    branches:
      - main
jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Clear decoded.txt
        run: echo "" > decoded.txt
      - name: Decode content
        run: |
          while read link; do
            content=$(curl -s $link)
            if [[ $content =~ ^[A-Za-z0-9+/]+={0,2}$ ]]; then
              echo $content | base64 --decode >> decoded.txt
            else
              echo $content >> decoded.txt
            fi
          done < Base.txt
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add decoded.txt
          git commit -m "Update decoded content"
          git push origin main
